### ISSUE TITLE
Checking if a field with a default value has been set

### ISSUE THREAD

**Issue by deepakmerugu** [dcodeIO/protobuf.js#200]
I'm trying to figure out if an optional field has been set in a proto. Can you please explain how to check if a field has been set. Currently, I'm observing that if a field has a default value and is not set, then on decoding, the object contains the default value. How can we distinguish this from the case where the field was indeed set with the same value as the default?

Thanks!

**Comment by seishun** [comment]
The official C++ and Java implementations provide `has_*` methods for this functionality. But JavaScript can do better than that. Here's an API that I think would be idiomatic for JavaScript:

Consider a Message object `obj` and a field "foo".

* `obj.foo` evaluates to the value of "foo" if it's set, otherwise to the default value for "foo". If "foo" doesn't have an explicit default, then it evaluates to the type-specific default.

* `"foo" in obj` is `true` if "foo" is set, otherwise `false`.

* `delete obj.foo` clears "foo". Afterwards, `"foo" in obj` is `false` and `obj.foo` is the default value.

This API could be implemented by using inheritance and `Object.defineProperty`. I can produce a proof-of-concept if anyone is interested.

**Comment by dcodeIO** [comment]
Closing this for now.

[protobuf.js 6.0.0](https://github.com/dcodeIO/protobuf.js/releases/tag/6.0.0)

Feel free to send a pull request if this is still a requirement.
