### ISSUE TITLE
Message constructor sometimes crashes when passed a message

### ISSUE THREAD

**Issue by murgatroid99** [dcodeIO/ProtoBuf.js#238]
To replicate:

```js
var ProtoBuf = require("protobufjs");
var builder = ProtoBuf.newBuilder();
builder.define("Test");
builder.create([
  {
    name: "Point",
    fields: [
      {
       rule: "optional",
       type: "int32",
       name: "x",
       id: 1
     },
     {
       rule: "optional",
       type: "int32",
       name: "y",
       id: 2
     }
    ]
  }
]);
var Test = builder.build("Test");
var Point = Test.Point;
var p = {x:0, y:0};
var p_msg = new Point(p);
// this crashes
new Point(p_msg);
```

To me, this is unexpected behavior because `p` appears to be identical to `p_msg` in every relevant way.

**Comment by vgatto** [comment]
I've also noticed this when using gRPC when I attempt to respond with a message that I've deserialized from backend storage. I forked the repo to attempt to fix the constructor, but I don't think it's possible since the constructor is ambiguous.

From Message.js:

```
var Message = function(values, var_args) {
    ProtoBuf.Builder.Message.call(this);
    // Create virtual oneof properties
    for (var i=0, k=oneofs.length; i<k; ++i)
        this[oneofs[i].name] = null;
    // Create fields and set default values
    for (i=0, k=fields.length; i<k; ++i) {
        var field = fields[i];
        this[field.name] = field.repeated ? [] : null;
        if (field.required && field.defaultValue !== null)
            this[field.name] = field.defaultValue;
    }

    if (arguments.length > 0) {
        var value;
        // Set field values from a values object
        if (arguments.length === 1 && typeof values === 'object' &&
            /* not another Message */ typeof values.encode !== 'function' &&
            /* not a repeated field */ !ProtoBuf.Util.isArray(values) &&
            /* not a ByteBuffer */ !(values instanceof ByteBuffer) &&
            /* not an ArrayBuffer */ !(values instanceof ArrayBuffer) &&
            /* not a Long */ !(ProtoBuf.Long && values instanceof ProtoBuf.Long)) {
            this.$set(values);
        } else // Set field values from arguments, in declaration order
            for (i=0, k=arguments.length; i<k; ++i)
                if (typeof (value = arguments[i]) !== 'undefined')
                    this.$set(fields[i].name, value); // May throw
    }
};
```

The constructor has two paths: work with a single object representing all fields, or work with positional arguments.

The offending line for this particular issue is:

```
/* not another Message */ typeof values.encode !== 'function' &&
```

which forces a single arg constructor from a Message instance to incorrectly try to handle arguments as positional.  I don't understand why this restriction is present. However, just commenting out this line breaks other tests because these two branches are not mutually exclusive. Consider the following protos:

```
message Inner {
  optional int32 id = 1;
}

message Outer {
  optional Inner inner = 2;
}
```
and the following two constructor calls:
```
new Outer({inner: { id: 1234 }});
new Outer({id: 1234});
```

Without more information about types (which can't be provided by plain old javascript), there is no way to support both of these without arbitrarily preferring one over the other (the pathological case being an empty message, which is indistinguishable). 

IMO, positional arguments should be dropped entirely.

**Comment by murgatroid99** [comment]
@vgatto The use case you describe is the exact reason I found this bug (as the issue reference above indicates). There actually is a fairly simple way to modify gRPC to avoid this problem, but it would require pull request #248 to be merged.

**Comment by vgatto** [comment]
Good to know!  Right now we're working around this using deepcopy.
