### ISSUE TITLE
float variable in protoBuf

### ISSUE THREAD

**Issue by mj-mehdizadeh** [dcodeIO/protobuf.js#463]
Hi everyone
i use protobuf for my project i have simple class that have float variable
when i set this variable with float value this is store wrong value

```
var ProtoBuf = dcodeIO.ProtoBuf;
        var builder = ProtoBuf.newBuilder({ convertFieldsToCamelCase: true });

        ProtoBuf.loadProtoFile('Test.proto', builder);
        var root = builder.build('proto');


        var encode = new root.Test(100.1)
        var buf = encode.toArrayBuffer();

        var decode = root.Test.decode(buf)
        console.log('decode code', decode.getCode());
```
and Test.proto its like this : 
```
syntax = "proto3";
package proto;

message Test {
    float code = 1;
}
```

i set 100.1 in code variable and in console log it print 100.0999984741211 why ??

**Comment by dcodeIO** [comment]
Because 100.1 cannot be represented perfectly within the boundaries of a float.

https://en.wikipedia.org/wiki/Floating_point#Accuracy_problems

**Comment by valerii-zinchenko** [comment]
Hi everyone!

I would like to bring up again the attention to this, because on our project we trapped onto this and I think that this is an issue. I agree about precision boundaries, but 32-bit format was not designed and used by people to work with the exact value represented in binary. I think, the idea was to have a big enough storage space in order to full fill some precision for decimal numbers. 

According to this https://en.wikipedia.org/wiki/IEEE_754#Basic_and_interchange_formats for 32-bit number only 7 decimal digits sould be taken into account (also stated here: https://en.wikipedia.org/wiki/Decimal32_floating-point_format). From my understanding, it means that only 7 significant digits can represent a stored value, other digits are like a noise created during conversion from binary to decimal.

I would like to propose to add rounding like this:
```js
const value = new Float32Array([101.1])[0];	// is like this https://github.com/protobufjs/protobuf.js/blob/master/lib/float/index.js#L131
parseFloat(value.toPrecision(7));
```

I also would propose to add similar rounding for 64-bit number with precision 16 (taken from the documents above):
```js
const value = new Float64Array([101.1])[0];
parseFloat(value.toPrecision(16));
```

Because there is no `101.1` number stored in 64-bit. At this point we are safe now, because all numbers in JS are 64-bit numbers and applying internal rounding, that is why they are displaying to us correctly. But if at some point the JS number precision will be increased (for example up to 128), then the simple `101.1` as double will be decoded and displayed like this:
```js
console.log((101.1).toPrecision(36));
```
will print `101.099999999999994315658113919198513`, like an issue we currently have for a `float` number.

Here is more increased precision just for example:
```js
console.log((101.1).toPrecision(60));
```
prints `101.099999999999994315658113919198513031005859375000000000000`

**Comment by valerii-zinchenko** [comment]
Hi, again! I understand that that is a matter of a representation. I also found a way to apply a precision rounding to full-fill our needs. So here is the code, in case anyone also trapped into this:

```js
class MyReader extends Protobuf.Reader {
    float() {
        return parseFloat(super.float().toPrecision(7));
    }
}
```

and here is how it is using by decoding:

```js
decoder.decode(new MyReader (new Uint8Array(data)));
```
