### ISSUE TITLE
Use it with protoC

### ISSUE THREAD

**Issue by pronebird** [dcodeIO/protobuf.js#504]
Hey,

I am trying to put together a simple example and I defined protocol file and used protoC to compile it into javascript objects. However I stumble upon error when importing those generated files:

> ReferenceError: goog is not defined

Is there any compatibility with what protoC produces and why protobuf.js does not mention its use. Are those two different things?

**Comment by dcodeIO** [comment]
protoc exclusively emits code for use with [google's js implementation](https://github.com/google/protobuf/tree/master/js).

The reason why protobuf.js exists, basically, is that using google's solution doesn't make a lot of sense without using the entire google toolkit. For example, google's js implementation pulls dependencies from its closure library (that's the error you get there, from goog.provide/require), which more or less requires using closure compiler etc. to eliminate unused code and whatnot.

protobuf.js, on the other hand, does not depend on google's toolkit but unfortunately isn't compatible with what protoc generates because both solutions differ significantly.

There are plans to integrate generation of es5/es6/ts classes into pbjs, which is somewhat the pendant to protoc here, but this hasn't been done yet because it isn't absolutely required. protobuf.js is capable of reading .proto files or pre-parsed .json files and generate fast code at runtime, so this doesn't really matter for performance.

The tools for static code generation are already there, though, and can be used to build custom solutions in the meantime: https://github.com/dcodeIO/protobuf.js#using-custom-classes

**Comment by pronebird** [comment]
@dcodeIO  Thanks for detailed answer!
