### ISSUE TITLE
Messages with no fields

### ISSUE THREAD

**Issue by fwny** [dcodeIO/protobuf.js#519]
I tried to create a message without any fields but when encoded it just gives an empty buffer as output.

Shouldn't it encode a message with header information so that the buffer can be decoded and the message type can be determined even though the message itself contains no fields? I am trying to integrate with a 3rd service which uses empty messages for signalling.

**Comment by fwny** [comment]
Nevermind, contacted the 3rd party and they're layering extra things to identify messages.

Thanks!

**Comment by dcodeIO** [comment]
If I'm not completely mistaken on this, an empty message that's not part of another message as a field value just encodes to an empty buffer. If you need a length-prefixed message, you can use `encodeDelimited` instead of `encode`, which prepends the message's length (here: 0) as a varint.

A message gains a tag (consisting of a field id and wireType 2) only when it is the value of another message's field. More precisely, the field becomes tagged.
