### ISSUE TITLE
Example for how to work with oneofs

### ISSUE THREAD

**Issue by spiderkeys** [dcodeIO/protobuf.js#523]
I've been hunting around for some up to date documentation that explains the basics of how to work with oneof fields in protobuf.js v6, but haven't been able to find anything. If there are some examples, could you point me in the right direction, and if not, would you mind giving a brief example of creating, encoding, and decoding a message that has a oneof field? Thanks.

**Comment by spiderkeys** [comment]
After messing around a bit longer, I got to something that seems to be working, but I'm not sure if this is the proper approach:

For a proto file "simple.proto":
```
syntax = "proto2";

message MsgType1 {
    required int32 value = 1;
}

message MsgType2 {
    required bool value = 1;
}

message MsgType3 {
    required int32 value1 = 1;
    required int32 value2 = 2;
}

message MyMessage {
    required uint32 uid = 1;
    required uint32 pid = 2;
    required uint32 utime = 3;

    oneof payload {
        MsgType1 msg1 = 4;
        MsgType2 msg2 = 5;
        MsgType3 msg3 = 6;
    }
}
```

```js
const protobuf = require( "protobufjs" );

protobuf.load("simple.proto", function(err, root) 
{
    if (err) throw err;
    
    // Lookup message type
    var MyMessage = root.lookup("MyMessage");

    // Create
    var myMessage = MyMessage.create( 
    {
        uid:1,
        pid:2,
        utime:3,
        msg2: { value: true},
        msg1: { value: 7}
    });

    // Encode
    var bb = MyMessage.encode( myMessage ).finish();

    // Decode
    var decodedMessage = MyMessage.decode(bb);
    var which = decodedMessage.payload;
})
```

Anything more to this? More idiomatic approach?

**Comment by dcodeIO** [comment]
Using `MyMessage.create` (just as you do) instead of plain objects is recommended when using oneofs, because runtime messages have virtual oneof properties with proper side effects.

```js
    var myMessage = MyMessage.create( 
    {
        uid:1,
        pid:2,
        utime:3,
        msg2: { value: true},
        msg1: { value: 7}
    });
```
When creating a message with oneofs, the last declared field value that is part of the oneof will cause the virtual oneof field to be set to this field's name (here: payload = "msg1"). Other field values part of the same oneof will be deleted (here: msg2, only msg1 is encoded). (see: [Prototype constructor](https://github.com/dcodeIO/protobuf.js/blob/master/src/prototype.js#L29), [setVirtual](https://github.com/dcodeIO/protobuf.js/blob/master/src/inherits.js#L180))

When decoding, the virtual oneof field should point to the field name of the last field of the oneof that was present on the wire. However, if multiple fields were present (which should be prevented usually), all of the present field values are set. (see [getVirtual](https://github.com/dcodeIO/protobuf.js/blob/master/src/inherits.js#L171) - this actually returns the *first* field's name currently, but should return the last I believe; need to look this up in the encoding reference).

When working with oneofs, like changing the field, you can set the virtual oneof field to the field name of the field you want to be the sole field to encode (see setVirtual above):

```js
myMessage.msg2 = ... ;
myMessage.payload = "msg2"; // deletes msg1 - use .setPayload("msg2") to support IE8
```

**Comment by spiderkeys** [comment]
Great, thanks for the additional information and for the great work you've put into this!

**Comment by opengpu** [comment]
is there other better way for decodedMsg than the code below?
`switch(decodedMessage.payload)
{
case "msg1":
break;
case "msg2":
break;
case "msg3":
break;
case "msg4":
break;
defalut:
break;
}
`

**Comment by doom-goober** [comment]
@dcodeIO 
Are virtual oneof properties broken in 6.8.8 or am I doing something wrong? I have this proto:

`message TestMessage
{
    oneof oneofMessage
    {
        StringMessage oneofStringMessage = 6;
        IntegerMessage oneofIntegerMessage = 7;
    }
}`

And this code:
`    const payloadIn = {
        oneofIntegerMessage : { integerValue : 5}
    }; 
 
    let errorMessage = testMessageDescriptor.verify(payloadIn);
    if (errorMessage) {
        throw Error(errorMessage); //Does not throw, valid.
    }
    const testMessage = testMessageDescriptor.create(payloadIn);
    testMessage.oneofStringMessage = { stringValue : "sss"};
    testMessage.oneOfIntegerMessage = { integerValue : 5 };
 
    errorMessage = testMessageDescriptor.verify(testMessage.toJSON());
    if (errorMessage) {
        throw Error(errorMessage); //Throws! multiple values
    }`

Actual:
Proto message has a oneof. We create a message instance using create(). We set values on BOTH oneof fields. We convert the message instance to json then verify the json. The verify fails because the JSON contains both values, violating the oneof rule.

Desired:
When we set the value on the second oneof field, the first oneof field should be unset because the virtual property should unset the first one.

Am I missing something? Thanks for protobufjs. I've been loving it except for this one thing.

**Comment by doom-goober** [comment]
> When working with oneofs, like changing the field, you can set the virtual oneof field to the field name of the field you want to be the sole field to encode (see setVirtual above):
> 
> ```js
> myMessage.msg2 = ... ;
> myMessage.payload = "msg2"; // deletes msg1 - use .setPayload("msg2") to support IE8
> ```

I feel like this should be in the documentation as it's a pretty common case.

**Comment by DevasiaThomas** [comment]
> is there other better way for decodedMsg than the code below? `switch(decodedMessage.payload)` 

I would like to know as well, particularly since this property is added using ``Object.defineProperty()`` and its resolved at runtime, not very IDE friendly. Warns that it's an unresolved field.  Are we supposed to use a getter instead of directly referencing this field?
