### ISSUE TITLE
Check if property is part of proto schema

### ISSUE THREAD

**Issue by subk** [dcodeIO/protobuf.js#526]
Is there a way to check if a plain object is valid regarding to its protobuf message type ?
If I remember correctly, protobufjs v5 was doing so before encoding a message.

I didnt find a way to do it in protobufjs v6

Eg, given this proto :  
```proto
syntax = "proto3";
package test;
message Foo {
  string bar = 1;
}
```

```javascript
const foo = root.lookup('test.Foo');

// should not throw
const validMessage = foo.create({ bar: 'foobar' });

// should throw an Error as 'xyz' is not a valid field
const invalidMessage = foo.create({ bar: 'foobar', xyz: 123 });
```

**Comment by dcodeIO** [comment]
There is `verify` which checks for missing required fields and invalid enum values. In your example:

```js
foo.verify(validMessage); // returns null if the message is considered valid, otherwise a string why it is not
```

`verify` does not type-check (yet), so encoding may still throw if present field values are entirely bogus.

The reason why this has its own method is performance. Let's say you already know for sure that the message is valid, because you double checked it, which I for example usually do, then calling verify implicitly would be unnecessary.

**Comment by subk** [comment]
Ok, it makes perfect sense from a performance point of view.

However I found protobufjs v5 behavior was quite useful and very explicit on errors (eg. when trying to call a service method with wrong arguments for example)

Not sure to understand how `verifier.generate` works, but would you be interested in a PR on `verifier.fallback` which will :  
- check `message` for valid properties
- type-check `message` valid properties

**Comment by dcodeIO** [comment]
I will probably go ahead and refactor the code generator anyway.

Somewhat related: https://github.com/dcodeIO/protobuf.js/issues/521

The resulting implementation would then not just have code generation for encode, decode and verify but also for initialize and convert (to JSON). I'd then also update the verifier to perform type-checking as this is in fact quite useful.

**Comment by subk** [comment]
Ok :+1: 
I will keep an eye on [#521](https://github.com/dcodeIO/protobuf.js/issues/521) too
Thanks

**Comment by dcodeIO** [comment]
Array and object defaults are not also on the prototype. This should fix your issue.

Caveat: You have to make sure to set new objects for these defaults on the actual instances. You can't just `Array#push` or `obj.something = 123;` on these objects. For example, if your object has a repeated field and you want to set values for it, use `myMessage.myRepeatedField = [ "a", "b" ]` instead of trying to modify the object.

**Comment by dcodeIO** [comment]
This commit adds type checking to the verifier. It's quite strict. Let me know if you experience any issues.
