### ISSUE TITLE
pbjs static-module and `from` (JSON)

### ISSUE THREAD

**Issue by mmikulicic** [dcodeIO/protobuf.js#588]
protobuf.js version: 6.3.1

How can read JSON data with `static-module` ?

With dynamic modules I can just do:

```
protobuf.load("src/foo.proto").then(function(root) {
  var Bar = root.lookup("bar");
  return bar.from({baz: {qux: 3}});
});
```

and it yields `Message { baz: Message { qux: 3 } }`

However, the code generated with `pbjs -t static-module` only defines the `create` method, which doesn't create the right child object types.

This is particularly painful when having things like `oneof` which depend on functionality defined in the generated type's protototype to guide the encoding (and thus basically encoding an empty message since it cannot determine which field of the `oneof` to render).

Should we just generate the `from` method ?

**Comment by dcodeIO** [comment]
I have also been thinking about how to handle this properly. Currently, converters rely on reflection information to find out how to handle field values, which is why it isn't supported for static code yet, as it has no reflection capabilities.

Not only for performance, converters would benefit from code generation just like encoders and decoders do, which would also allow us to generate the missing from/asJSON methods statically.

The reason why I didn't implement this yet is that static code s quite large already, and especially converters would allow an alternative: Field names could be mapped to converter functions (i.e. something like ensureLong for long fields) instead of code generation, only at the cost of additional function invocations and hashmap lookups - or this could be implemented in a hybrid form eliminating the lookups. Haven't come to a conclusion, yet.

**Comment by mmikulicic** [comment]
I wouldn't mind using the reflection code; I use the generated code mainly because:

1. it supports TS.
2. when rendering to string it shows the message type name.

would it be possible to achieve these goals in some different way?

**Comment by dcodeIO** [comment]
Closing this for now as 6.4.0, which is now released, should solve the issue. Feel free to reopen the issue if necessary.

**Comment by dcodeIO** [comment]
@mmikulicic: This now generates named constructors just like static code does and it should already be possible to use a static .d.ts with its json-module counterpart.
