### ISSUE TITLE
arraybuffer

### ISSUE THREAD

**Issue by mj-mehdizadeh** [dcodeIO/protobuf.js#589]
Why ```protobuf.js``` cannot decode ```arraybuffer```? And I must convert it to ```Uint8Array```
```javascript
var xhr = new XMLHttpRequest();
xhr.open(
    /* method */ "GET",
    /* file */ "/path/to/encodedSomeMessageData.bin",
    /* async */ true
);
xhr.responseType = "arraybuffer";
xhr.onload = function(evt) {
    var msg = SomeMessage.decode(xhr.response);//Don't Works
    //var msg = SomeMessage.decode(new Uint8Array(xhr.response));//Works
}
xhr.send(null);
```

**Comment by dcodeIO** [comment]
protobuf.js requires a byte-level view on the data, which is provided by Uint8Array in the browser (falls back to Array in older browsers) or Buffer under node.js. You are actually not converting the ArrayBuffer there, but wrapping it in a byte-level view.

This is done because decoders work pretty much the same in all environments, and an additional check for ArrayBuffer would usually be unnecessary overhead under node.js / in older browsers / where Uint8Array is used anyway.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by scaret** [comment]
+1
