### ISSUE TITLE
uses unsafe-eval

### ISSUE THREAD

**Issue by diracdeltas** [dcodeIO/protobuf.js#593]
protobuf.js version: 6.3.x

it appears that recent versions of protobufjs are using `eval`, which prevents the browserified library from working in web applications that have a Content Security Policy without `unsafe-eval`, such as is the case for [Chrome extensions](https://developer.chrome.com/extensions/contentSecurityPolicy).

```
EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: default-src 'self'
```

**Comment by dcodeIO** [comment]
Fallback encoders and decoders were rather slow and large, so I decided to remove them entirely. The alternative here is generating [static code](https://github.com/dcodeIO/protobuf.js#command-line) instead.

**Comment by dcodeIO** [comment]
Closing this issue for now as it hasn't received any replies recently. Feel free to reopen it if necessary!

**Comment by kalitine** [comment]
I'm generating static code, but still got this warning with RollupJS:
```
@protobufjs/inquire/index.js (12:18) Use of eval is strongly discouraged, as it poses security risks and may cause issues with minification
```

Does it exist some compile option to prevent using `eval`?

**Comment by dcodeIO** [comment]
[See](https://github.com/dcodeIO/protobuf.js/blob/master/lib/inquire/index.js)

What's happening there is that the `long` module is require-d only if available in the environment.

**Comment by kalitine** [comment]
I see. I'll take a closer look this weekend and see how to get rid of `eval` without breaking this functionality, if it's ok for you.

**Comment by dcodeIO** [comment]
Sure. Not a big fan of the eval solution either. Just seemed to be the only workaround reliably preventing warnings and stuff in webpack.

**Comment by kalitine** [comment]
I wasn't able to find a common solution which muches all scenarios. This problem is about different bundle tools: Webpack, Rollup, Browserify etc. 
For example in Rollup if the `inquire` function would like this:
```javascript
function inquire(moduleName) {
     try {
         var mod = require(moduleName)
         if (mod && (mod.length || Object.keys(mod).length))
             return mod;
     } catch (e) {
       return null;
     } // eslint-disable-line no-empty
     return null;
 }
```
It's good enough to not have any errors or warnings on build. But Webpack understands this code and still will try to extract some information (https://webpack.js.org/guides/dependency-management/). I do not know much about Browserify, but I suppose to have this kind of problem too.

What is common among theses bundlers is that it is possible to specify **externals**.
Webpack: https://webpack.js.org/configuration/externals/
Browserify: https://benclinkinbeard.com/posts/external-bundles-for-faster-browserify-builds/#marking-dependencies-external
Rollup: just does not care about require, because is cares only about ES2015 modules.

Thus I think one of the solution would be to use `require` function as it without `inquire` and specify in documentation the externals dependencies of protobufjs. API consumers will be aware of those dependencies and would be able to specify it in their configuration specific to their bundler tool.

Of course this solution require an additional step for API consumers, but eliminates the `eval` problem and also make clients to be aware of the externals depending on the environment.

**Comment by dignifiedquire** [comment]
@dcodeIO any thoughts on this? I am trying to switch to this library to get rid of unsafe-evals and this is an issue for me, maybe using `long` at all could be compile flag?

**Comment by kalitine** [comment]
Temporary solution could be to use a preprocessor. For example for Rollup is `rollup-plugin-re`:
```javascript
import replace from 'rollup-plugin-re'
// ...
plugins: [
      replace({
        patterns: [
          {
            test: /eval.*\(moduleName\);/g,
            replace: 'undefined;'
          }
        ]
      })
    ]
// ...
```

**Comment by BichengWang** [comment]
met same problem. Is there any long term solution?

**Comment by alejandroclaro** [comment]
Any news about this issue?

I have the same problem.

My two cents here. The proposed solution can be improved by using `require.resolve` instead of expeting an exception if the module is not present.

**Comment by yvele** [comment]
There is an easy workaround for eval like this one https://github.com/aws/amazon-chime-sdk-js/issues/800#issuecomment-713733976

But now I'm struggling with codegen that has the same problem: https://github.com/protobufjs/protobuf.js/issues/1483 😕
Why is codegen used for reflection? 🤔  is it possible to replace it?

**Comment by paralin** [comment]
@dcodeIO using `eval` throws a lot of errors in `esbuild` as well.

**Comment by MentalGear** [comment]
Is this `eval` trick still needed for `require` ? Maybe it was an issue in 2016 when this issue was introduced, but with modern build tools, it should be safe to replace. Using `eval` is the bigger hindrance since modern browsers and extensions do not allow `unsafe-eval` in their CSP (Content Security Policy).

Alternatively, I'd be great if at least the `eval` usage could be made option-able via a flag.
