### ISSUE TITLE
when a object is set for an array field in json, converting to proto does not throw an error

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#601]
Instead it seems like  a bad bytestream is generated which throws error on the server side in Java protobuf.
It would be great to enforce type mismatch checks for all fields.

**Comment by dcodeIO** [comment]
`Type#verify` and `Message.verify` are meant for this. Internally, encoders just look for a true-ish value with a non-zero .length property.

**Comment by r-tock** [comment]
Even with verify, it is getting encoded to wrong byte stream. 

message MyProto {
  repeated MyArrayMessage msg = 1;
}

message MyArrayMessage {
  optional string astring = 1;
}

MyProto.from({ msg: { astring: "foo" } }); succeeds.

**Comment by dcodeIO** [comment]
`verify` should [return an error message](https://github.com/dcodeIO/protobuf.js/blob/master/src/verifier.js#L127).

What I'd expect in your example is that MyProto#MyArrayMessage is not present on the wire at all because `{ astring: "foo" }´ does not have a `.length` property. As I mentioned previously, this is because the most efficient check for repeated fields is `if (field && field.length) ...`.

**Comment by r-tock** [comment]
Hmm, yes, the behavior has changed now at Head from when I originally tested it. Yes, it's silently dropping it from the wire.

Can you throw an error instead in the .from method. verify is not doing anything.

**Comment by dcodeIO** [comment]
Verify doesn't throw but return the error message as a string. You could throw that as an error yourself if you wish.

**Comment by r-tock** [comment]
verify is returning `null` for me.

**Comment by r-tock** [comment]
I presume the value is ignored in the proto at the end of from call. So verify is not doing anything.

**Comment by dcodeIO** [comment]
It really should [return something](https://github.com/dcodeIO/protobuf.js/blob/master/src/verifier.js#L145) if the value does not fulfull `Array.isArray`.

**Comment by dcodeIO** [comment]
Ah, yes, `from` makes the same assumption, only copying values `if (value && value.length)` as it needs to convert each value accordingly.

**Comment by r-tock** [comment]
yeah, would be great if somehow parse errors for `from` was propagated. It will bring a whole lot of sanit, robustness and maintainability to the code. I am even fine with making this strict errors.

**Comment by r-tock** [comment]
Just saw your edited question

We have a react-redux app, most of the application state is managed in JSON (because of ease of serializability into local-storage and back). We have built an AJAX middleware which deals with proto byte-stream request/response to the server. Before we do an AJAX request, we convert JSON to proto. This is literally everywhere! So when we convert from JSON to proto, if there are mistakes, we would love to have errors thrown at the conversion stage so that we don't send anything invalid value to the server (even silently)

For new code we are using create() but most of the messages are pretty small so dealing with them in JSON and then converting that to proto before calling the middleware is a common pattern.

**Comment by dcodeIO** [comment]
I see, hmm. Well, currently converters really just convert any values as you can also see [here](https://github.com/dcodeIO/protobuf.js/blob/master/src/converter.js#L43) for example. Hence, no matter what is set, it is converted through `Number`, `String`, `Boolean` etc. Adding assertions everywhere would probably be too much, considering that numbers could be provided as strings intentionally (i.e. because stored as object keys or something) or by mistake, which cannot be reliably distinguished.

One possibility, though, that doesn't conflict with this would be to change how non-arrays are converted to arrays. Let's say you specify an object for a repeated field, then it converters could wrap this object in a new array instead. Would that be helpful?

**Comment by r-tock** [comment]
@dcodeIO yes, that was the v5 behavior, which a part of our code unknowingly used and got it working v5 that broke in v6 due to which I found this issue. Every cell in my body is screaming that this is silent conversion is a bad thing, but from a compatibility standpoint it is probably ok to do. I am fine with either throwing errors for non-repeated on a repeated or silently converting them. I prefer the former even if it means more work on my part to clean up our code-base
