### ISSUE TITLE
update @types/protobufjs defintion

### ISSUE THREAD

**Issue by frediana** [dcodeIO/protobuf.js#628]
protobuf.js version: ^6.3.1

Using typescript, I tried to import the protobufjs typescript definition from https://www.npmjs.com/package/@types/protobufjs using npm i @types/protobufjs.

It works but the definitions are v5 compatible instead of v6.3.1. 

When using index.d.ts from protobujs it works fine. 

I think latest index.d.ts must be pushed to @types/protobufjs.

**Comment by frediana** [comment]
I would have done it, but not sure I have rights to push to this npm repo.

**Comment by dcodeIO** [comment]
If I understood this correctly, it's actually recommended to ship typings with the actual module, while the @types namespace on npm is rather a fallback mechanism for libraries that do not have any typings on their own.

If you create a PR there today, the typedef will be outdated and maybe incompatible again tomorrow. Instead, you should probably just use the one shipped with (your version of) the module.

If there is an issue, it is either in your IDE not using the correct typings or in the way protobuf.js exposes its typings.

**Comment by frediana** [comment]
Yes indeed, you're right.

**Comment by dakom** [comment]
I'm relatively new to typescript and may misunderstand the ecosystem, but it seems to me that there is an advantage to separating the types as a distinct package where the project is for the browser. In other words, the protobuf.js library code is included via cdn or html <script> tags (not import) and development is done in typescript. 

In that case- importing the node module would cause a number of possible mistakes:
1. Double-bundling (i.e. it's imported via html, and then again via webpack etc. due to the import())

2. Version differences (i.e. an npm install/update being a different version than the html/cdn included one)

These can be avoided (i.e. using import but also webpack excludes) - but the point is that isolating the typings to only be available via the package has its own set of problems that need to be considered

**Comment by dcodeIO** [comment]
Module authors don't have access to the @​types org on npm usually. Typings are pulled from there. As far as I understood the recommended way of publishing typings is with a module, while the @​types namespace is used to distribute typings for modules that do not have typings on their own.

**Comment by dakom** [comment]
fwiw I believe this works to get typings from the module but use the lib from cdn:

In code:
`import * as protobuf from 'protobufjs';
[...]
protobuf.load(...);
`

In html:
`<script type='text/javascript' src='//cdn.rawgit.com/dcodeIO/protobuf.js/6.7.3/dist/protobuf.min.js'></script>`

In webpack config:
`externals: [{
    protobufjs: 'protobuf'
  }]`
