### ISSUE TITLE
How to use pbjs&pbts to generate *.d.ts file correctly with command line?

### ISSUE THREAD

**Issue by shippomx** [dcodeIO/protobuf.js#646]
protobuf.js version: <protobuf.js 6.0>

I use these command lines to generate a *.d.ts file, but it dosen't work smoothly: 

pbjs languages.proto -t static-module -o languages.js
pbts languages.js -o language.d.ts --no-comments

but when I use the language.d.ts file in nodejs, it occurs a series of errors:
error TS2391: Function implementation is missing..

what should I do to get the right *.d.ts file? 
thx for your help :)

[languages.zip](https://github.com/dcodeIO/protobuf.js/files/707802/languages.zip)

**Comment by dcodeIO** [comment]
You should really use something more recent than `6.0`, i.e. `6.4.6`.

With that in mind, this looks correct to me:

```
pbjs -t static-module -o languages.js languages.proto
pbts -o language.d.ts --no-comments languages.js
```

**Comment by shippomx** [comment]
Yep, it works when I upgrade the protobufjs. Happy!!!

**Comment by ehallander9591** [comment]
Realizing that this is a closed topic, it does bring up an interesting point. The generated .d.ts is yes a definition file, however I wonder what I need to do so that I can avoid the pattern for usage that I have been using and use a pattern a pattern that works more consistently like other modules. My own ignorance could be the problem here.

For example, I am using the static module generated code, and to us that in my typescript code I have to write something like
```
let mpxs = require("../../srcGen/js/mpxsStaticModule");

let newObj = mpxs.com.eoir.mpxs.Request.create();
```

and if I pass newObj along as a parameter I can have a signature that looks like

```
import {com} from "../../srcGen/ts/mpxsStaticModule";

function someFunction(obj:com.eoir.mpxs.Request) {
}
```

Webstorm does a better job with import {com} for code completion than it does with above require statement. 

I can write something like
```
import {Socket} from "zmq";
```
and I get the code completion and the implementation 

I probably need to explore packaging my generated static module and the associated .d.ts so that it loads like a package.

Just musing.

**Comment by dcodeIO** [comment]
The following should be mostly equivalent to the require statement, but uses import:

```ts
import * as mpxs from "../../srcGen/ts/mpxsStaticModule";
```

**Comment by ehallander9591** [comment]
I was just musing :).

I configured to package.json files, one for the .d.ts and one for the staticModule and packaged them into a tarball for a local install into my projects node_modules. Then I was able to change my code to

```
import {com} from "myModule"
```

and get both code completion assistance and functionality.

Glad you made me think about this! :)

Cheers

**Comment by shippomx** [comment]
Finally, I didn't choose the protobufjs to generate the *.ts file, because it requires the protobuf which is needed when "npm start", and invokes me "npm install protobuf", but it fails. I think the protobuf may be out of time.

I use the https://github.com/enjoypi/protoc-gen-ts instead. 
It generate the *.ts file from *.proto correctly and works smoothly in my project at the moment. 
Thanks your friendly help again.
