### ISSUE TITLE
Use const instead of var when outputting es6 descriptor

### ISSUE THREAD

**Issue by atrauzzi** [dcodeIO/protobuf.js#667]
I've got this in my descriptor/metadata:

```
var $root = ($protobuf.roots["default"] || ($protobuf.roots["default"] = new $protobuf.Root()))
```

Which makes my default-configured linter a little sad.  Maybe it's worth switching to `const` or failing that `let`?

**Comment by dcodeIO** [comment]
ES6 wrapper for reference: https://github.com/dcodeIO/protobuf.js/blob/master/cli/wrappers/es6.js

The $root var is generated on the JS side (shared for all sorts of static code), which is then just wrapped with the wrapper referenced above. What you can do today is providing a compatible linter configuration to `pbjs` with the `--lint` parameter. If you have another idea that still allows reusing the shared code part, let me know.

**Comment by atrauzzi** [comment]
Ah, I see.

What about separating the templating process out so that the `var $root` belongs to the ES5 specific side and then put `const $root = ` in the ES6 template and `var $root =` in the ES5 one?

**Comment by dcodeIO** [comment]
For reference:
* JSON module target: https://github.com/dcodeIO/protobuf.js/blob/master/cli/targets/json-module.js#L12
* Static target: https://github.com/dcodeIO/protobuf.js/blob/master/cli/targets/static.js#L43

As you can see there, `$root` definitions are slightly different depending on the type of module you are generating (JSON module uses `new Root()` while static code uses `{}`). That's why it is in the respective target's code. Hmm...

**Comment by atrauzzi** [comment]
I feel like I'm looking at something that resembles view logic in a web application. What would your thoughts be on pulling in a view engine as a dev dependency and doing lots of this declaratively?

**Comment by dcodeIO** [comment]
I'd rather avoid rewriting everything (again). Nonetheless, there is an `--es6` option now.

**Comment by atrauzzi** [comment]
Completely understandable.  I'll try it out this evening and if there are any issues, I'll reopen :)
