### ISSUE TITLE
Should the the interface definition for Long include toNumber?

### ISSUE THREAD

**Issue by johnnyreilly** [dcodeIO/protobuf.js#669]
protobuf.js version: 6.6.3

I noticed that the TypeScript definition for `Long` does not include `toNumber`:

https://github.com/dcodeIO/protobuf.js/blob/master/index.d.ts#L2001

Should it?  Something like:

```
toNumber(): number;
```

**Comment by dcodeIO** [comment]
index.d.ts includes just a minimal interface for `Long` to ensure that tsc doesn't throw any errors.

Long.js type definitions: https://www.npmjs.com/package/@types/long

**Comment by johnnyreilly** [comment]
There don't appear to be any Long.js type definitions?

**Comment by dcodeIO** [comment]
See link above, which is a package containing https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/long

**Comment by johnnyreilly** [comment]
Sorry - my mistake; it's just that package lacks a readme.  Shouldn't protobufjs take a dependency on @types/long rather than rolling it's own minimal version? Because the minimal version exposed by protobufjs won't be the same as the @types one unless you take that dependency.  I may be missing something here; please do set me straight if that's the case!

**Comment by dcodeIO** [comment]
protobuf.js [depends on it](https://github.com/dcodeIO/protobuf.js/blob/master/package.json#L61), yes. It's still an optional dependency, though, and not present everywhere, which is why it isn't strictly referenced.

When using both protobuf.js and long.js in your project, depend on both and `require` both. That should ensure that the long.js type definitions are present, too.

**Comment by johnnyreilly** [comment]
OK - thanks for the help
