### ISSUE TITLE
Missing array for repeated values

### ISSUE THREAD

**Issue by aakilfernandes** [dcodeIO/protobuf.js#671]
protobuf.js version: 6.5.3

I've got a protofile here
https://gist.github.com/aakilfernandes/659e04b61c8e2f9677cad60b5354c423

However when I decode, the `imageMultihashes` field is blank (i'm expecting an empty array).

Here's the data I'm using: 

`0a084d792053746f7265120275731a0022040a0012002a0c0a001206676c6f62616c1a00`

And here's my results

```
{
  "name": "My Store",
  "base": "us",
  "info": "",
  "products": [
    {
      "name": "",
      "info": ""
    }
  ],
  "transports": [
    {
      "name": "",
      "to": "global",
      "info": ""
    }
  ]
}
```

**Comment by dcodeIO** [comment]
How did you generate the result? Did you use `JSON.stringify?`? If so...

**Some background:**
* The empty array might not be showing up because it's actually on the prototype as a default value.
* The default `Message#toJSON` implementation, which is called transparently when using `JSON.stringify`, does not know about your intentions.

**Possible solutions:**
* Keep using the `Message` instance as is and you should find that there actually is an array where you'd expect it, it just won't show up with `JSON.stringify` - or -
* Change `protobuf.util.toJSONOptions` to modify `Message#toJSON`'s behavior globally - or -
* Use `Message#toObject` instead and specify your desired [conversion options](http://dcode.io/protobuf.js/global.html#ConversionOptions). Example:
  ```js
  var plainObj = myStore.toObject({ arrays: true }); // or, for default values in general: { defaults: true }
  ```

**Comment by aakilfernandes** [comment]
Thanks for the quick reply. I'll try out your suggestions

In the mean time i was able to recreate the issue (i believe) here

https://github.com/SafeMarket/protobuf.js/commit/bdb0e975dbc52df83fb9f34cc4d6348e900bd2d7

**Comment by aakilfernandes** [comment]
@dcodeIO I see it on the prototype. Thanks!
