### ISSUE TITLE
`decode()` fails silently when passing in a wrong type

### ISSUE THREAD

**Issue by tomergg** [dcodeIO/protobuf.js#695]
protobuf.js version: 6.6.5

When passing in a `ByteBuffer` instead of a `Uint8Array`, decode fails silently and return an "empty" `message`. Calling `toObject` on the message will return an empty object. The expected is to validate the input parameters and throw an exception if it's of an invalid type.

```js
try {
  const pbNotifications = pbRoot.lookup('Notifications');
  const data = new ByteBuffer(...);
  const notification = pbNotifications.Notification.decode(data).toObject();
} catch (error) {
  logger(error);
}
```

As a side note. I came across this bug after switching from v5 to v6. A part of the code, where the test coverage was not ideal, was failing silently. It was only discovered at functional QA time.

**Comment by dcodeIO** [comment]
I intentionally omitted these assertions because `decode` is called implicitly for each sub-message, which'd then execute the assertion over and over again. For example, if you have a .proto like...

```protobuf
message Outer {
   repeated Inner foo = 1;
}
message Inner {
}
```

..then you'd call `Outer.decode(...)` yourself, which implicitly calls `Inner.decode(...)` for each repeated element of `foo` and so on.

Your request is a valid issue, though. Ideally, there'd be an unchecked `_decode` for internal use and a checked `decode` for the API or something like that.

**Comment by tomergg** [comment]
Thank you again for the quick and detailed answer

> Your request is a valid issue, though. Ideally, there'd be an unchecked _decode for internal use and a checked decode for the API or something like that (also in static code).

This sounds like a good solution.  The issue is not blocking me in anyway. I quickly fixed my code and it's working well. It was an easy thing to miss moving from v5 to v6, since v5 used `ByteBuffer`. When this is addressed I think it would make it slightly easier to upgrade.

BTW,
v6.6.5 came just in time. We have a code freeze today.
Thank you again.

**Comment by dcodeIO** [comment]
Should be fixed in master.
