### ISSUE TITLE
Error on loadSync with options

### ISSUE THREAD

**Issue by yagop** [dcodeIO/protobuf.js#704]
protobuf.js version: 6.6.5

According with [docs](http://dcode.io/protobuf.js/Root.html#loadSync) `loadSync` accepts 2 arguments, the second one as the `options`. Looking into the [code](https://github.com/dcodeIO/protobuf.js/blob/6.6.5/src/index-light.js#L66-L70) the second arguments is the root namespace.

```js
const builder = ProtoBuf.loadSync(protoPath, {keepCase: true});
```

```
/tmp/prj/node_modules/protobufjs/src/index-light.js:69
    return root.loadSync(filename);
                ^

TypeError: root.loadSync is not a function
    at Object.loadSync (/tmp/prj/node_modules/protobufjs/src/index-light.js:69:17)
    at Object.<anonymous> (/tmp/prj/server/protobuf.js:6:31)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/tmp/prj/tests/proto.js:1:80)
```

**Comment by dcodeIO** [comment]
`Root#loadSync` (link "docs" above) differs from `protobuf.loadSync` (link "code" above). Bascially, `protobuf.loadSync` is more like a convenience function, while `Root#loadSync` has additional options.

**Comment by yagop** [comment]
My bad, didn't know the difference between `Root#loadSync` and `protobuf.loadSync`. Got it working with:

```js
const protobuf = require("protobufjs");
const root = new protobuf.Root().loadSync('./file.proto', {keepCase: true});
```

**Comment by nmccready** [comment]
@dcodeIO then what is the cleanest way to pass loadSync options down? This is kind of frustrating as I am blocked in passing `keepCase` options down to the parse both [here](https://github.com/dcodeIO/protobuf.js/blob/master/src/index-light.js#L66-L69) and in [google-proto-files](https://github.com/googleapis/nodejs-proto-files/blob/master/load.js#L44-L45) .

**Comment by dcodeIO** [comment]
The `protobuf.loadSync` function basically is a convenience function for simple things, with [`Root#loadSync`](https://github.com/dcodeIO/protobuf.js/blob/master/src/root.js#L232) accepting all the options. All you have to do for this is instantiate a `new Root` and use this instead instead of relying on `protobuf.loadSync` to return a new one.

**Comment by nmccready** [comment]
I hear yeah but this is a still a major pain with google-proto-files. Since [this class](https://github.com/googleapis/nodejs-proto-files/blob/master/load.js#L24-L42) is not exposed. 

> The protobuf.loadSync function basically is a convenience function for simple things, with Root#loadSync accepting all the options. All you have to do for this is instantiate a new Root and use this instead of relying on protobuf.loadSync to return a new one.

I was going to make my own loadSync function.
```
function loadSync(filename, options) {
  const root = new GoogleProtoFilesRoot();
  return root.loadSync(filename, options);
}
```
But due to that class being private I basically need to copy and reimplement that entire file.
