### ISSUE TITLE
field typings for `create`

### ISSUE THREAD

**Issue by masonk** [dcodeIO/protobuf.js#717]
protobuf.js version: 6.6

Thanks for a fantastic package. This is an enhancement request, something I would only make because I care! 

I'm using protobufjs to generate TS definition files, but I've noticed that the various creation methods such as `create`, `fromObject` and `new`, aren't typed with the allowable fields. This is important to me, because those fields are exactly the ones that I want intellisense for.

Are there any plans to add this? If not, would you accept a patch for them? (Would you be willing to guide me if I commit to adding this patch?)

**Comment by dcodeIO** [comment]
Still rather basic: This now documents an interface named like the message with a trailing "$Properties" and makes the message *implement* the new interface. Additionally, it references the properties interface as the type of the parameters to the constructor and `.create`.

However, parameter types of `.fromObject` and `.verify` are still plain objects because these methods are actually intended to be used with plain objects  but their types could be changed to reference both `(MyMessage|Properties|Object.<string,*>)=` instead if that helps. Let me know!

**Comment by masonk** [comment]
Can't wait to try this out tonight! Will let you know.

**Comment by tamird** [comment]
a75625d didn't quite do the right thing - for instance, it doesn't do objects-all-the-way-down. I get this generated definition:

```typescript
            type EventsResponse$Properties = {
                events?: cockroach.server.serverpb.EventsResponse.Event[];
            };
```

Where it should probably be:
```typescript
            type EventsResponse$Properties = {
                events?: cockroach.server.serverpb.EventsResponse.Event$Properties[];
            };
```
Note the $Properties on the inner array.

**Comment by dcodeIO** [comment]
Does that solve it?

**Comment by tamird** [comment]
Yes, but there is now also https://github.com/dcodeIO/protobuf.js/issues/723.
