### ISSUE TITLE
MessageType.verify should accept all values that MessageType.toObject can produce

### ISSUE THREAD

**Issue by murgatroid99** [dcodeIO/protobuf.js#748]
protobuf.js version: 6.7.0

For some conversion options, `verify` appears to reject some values that `toObject` can produce. For example, `longs: String` is a valid conversion option, but if a string is provided, `verify` outputs `uint_64: integer|Long expected`. Similarly, `enums: String` is a valid conversion option, but if a string is provided, `verify` outputs `enum_value: enum value expected`.

**Comment by dcodeIO** [comment]
This is intended and that's why `.fromObject` exists. Both `.encode` and `.verify`, which is the check for the former, expect a [valid message](https://github.com/dcodeIO/protobuf.js#valid-message).

> A valid message is an object not missing any required fields and exclusively using JS types for its fields that are understood by the wire format writer.

**Comment by dcodeIO** [comment]
Confusing diagram of what I just said:

![](http://dcode.io/protobuf.js/toolset.svg)

**Comment by dcodeIO** [comment]
I now also rephrased the [Usage](https://github.com/dcodeIO/protobuf.js#usage) section in this regard. Hope this helps.

**Comment by murgatroid99** [comment]
OK, I think I understand now. `verify` indicates that calling `create` or `encode` directly on the plain object will succeed. `fromObject`, on the other hand, does conversion from a broader range of plain objects to create valid messages.

**Comment by LarsOL** [comment]
We just encountered this discrepancy, in our situation we are transmitting json over the wire (from native GoLang/Java protobuf serializers ). We expected to call `verify` on the json followed by `create`, but it seems that `verify` expects a non standard internal format? 

Specifically 
```
message ReleaseRequest {
...
    google.protobuf.BoolValue test = 9;
    google.protobuf.Int32Value next = 10;

}
```
gets serialized into 
```
{
  "test": true,
  "next": 50
}
```
By both java and Golang reference implementations. But the `verify` expects test to be a object. Something like (??) : 
```
{
  "test": {
     value: true
  },
  "next": {
      value:50
   }
}
``` 
which is non standard?
From my understanding the only way for us to ingest the json is `fromObject`, though this seems to be a lot less strict in its checking?

**Comment by dcodeIO** [comment]
It's not non-standard, see: https://github.com/google/protobuf/blob/fd046f6263fb17383cafdbb25c361e3451c31105/src/google/protobuf/wrappers.proto#L99

There simply isn't a [wrapper](https://github.com/dcodeIO/protobuf.js/blob/master/src/wrappers.js) yet that deals with these types specifically, so the underlying .proto representation is used.

**Comment by LarsOL** [comment]
From my understanding the `verify` expects a raw  javascript object formed 'as is' protobuf message format, rather than the JSON version? 
The difference being that the protobuf JSON serialization/deserialization standard differs from the message format. As mentioned in that file 

> The JSON representation for `BoolValue` is JSON `true` and `false`.

I guess the confusion is then, which method is meant to deserialize JSON ,`fromObject`, or is `verify`? (assuming the wrapper get implemented)

Thanks for helping clarify

**Comment by dcodeIO** [comment]
`verify` is used to test whether an object meets the criteria of being a valid message. It doesn't deserialize. The different methods are described in detail [here](https://github.com/dcodeIO/protobuf.js#valid-message).

**Comment by jlisee** [comment]
This is an awesome library.  Such a join to work dynamically with protobuf types like this.  Which is why it's a bummer that I have the same issue as @dinesh-nadar.

I want to be able to use the default JSON mapping of enums to protobuf which is strings ([as documented here](https://developers.google.com/protocol-buffers/docs/proto3#json)), and at the same time I still want to be able to verify the validity of the object I am working with.

Right now I am using this code to pre-process the JSON objects calling `stringifyEnums(message, object)` before `message.verify(object)`, it's an OK workaround, but 

```javascript
function stringifyEnums(protoType, jsonObject) {
  const enumTypes = {};

  protoType.nestedArray.map(function store(e) {
    enumTypes[e.name] = e.values;
    return e;
  });

  const fields = protoType.fields;

  for (const fieldName in fields) {
    if (fields.hasOwnProperty(fieldName)) {
      const value = fields[fieldName];

      const values = enumTypes[value.type];

      if (values !== undefined) {
        stringifyEnumField(values, fieldName, jsonObject);
      }
    }
  }
}

function stringifyEnumField(values, fieldName, jsonObject) {
  const originalValue = jsonObject[fieldName];

  if (originalValue !== undefined) {
    const newValue = values[originalValue];

    if (newValue === undefined) {
      const msg = `Error: ${fieldName} not present on object`;
      throw msg;
    }

    jsonObject[fieldName] = newValue;
  }
}
```
