### ISSUE TITLE
How to ensure types for both JSON and proto representation in typescript

### ISSUE THREAD

**Issue by r-tock** [dcodeIO/protobuf.js#793]
This may be a help content question or a feature request

Since in the code we move from Proto to JSON and back to Proto at various places, is there a way to annotate types for the JSON version (given we are using conversion options long -> number, and enum -> string) in our typescript codebase.

Also, when is 6.8.0 releasing?

**Comment by dcodeIO** [comment]
You'll still require an explicit interface for fully typed toObject return values currently because their value types are configurable at runtime. There might exist some generics trickery, or, if having proper keys is sufficient, a construct like `type Properties<T> = { [P in keyof T]?: any };` might help. If you have another idea, let me know.

Regarding 6.8.0: Still need to catch up on issues, but aside from that there aren't any blockers I'd say.

**Comment by r-tock** [comment]
Can you create a type generator which can be used for JSON. So that we can add type annotations in the Json world. And would get stripped off after transpiling with ability to indicate types of long and enums fields

**Comment by r-tock** [comment]
@dcodeIO Thoughts on supporting code-gen for json types (with options).

**Comment by dcodeIO** [comment]
Maybe one day, but I am currently busy with webassembly things. Feel free to send a PR!

**Comment by r-tock** [comment]
Will do. Would you rather have me add that functionality into pbts or create a new cli tool?

with pbts I can add  the flags --output-json-types and --enum-type={enum|string|number} --long-type={number|long}

Unless you feel that takes away from the functionality of pbts.

**Comment by dcodeIO** [comment]
What do you think about having targets analogous to pbjs, with dts being the default?

**Comment by r-tock** [comment]
I think I can swing that. Will try and ping If I get stuck somewhere

**Comment by r-tock** [comment]
I think that PR has enough to generate types that work with JSON.

@dcodeIO Any chance you can get a release out soonish.
