### ISSUE TITLE
int64 not compatible with JSON.stringify

### ISSUE THREAD

**Issue by fiibbb** [dcodeIO/protobuf.js#937]
protobuf.js version: 6.8.0

When a int64 object is being converted by `JSON.stringify`, it gets converted into a string, not a number.

Given protobuf file:
```
> int64idl = 'syntax = "proto3"; package foo; message Int64 {int64 value = 1;}';
```

after parsing the file into a `int64msg`:
```
> proto = require('protobufjs');
> protoRoot = new proto.Root();
> proto.parse(int64idl, protoRoot);
> int64msg = protoRoot.lookup('foo.Int64');
```

encode then decode a json object then pass to JSON.stringify:
```
> JSON.stringify(int64msg.decode(int64msg.encode({value:42}).finish()))
'{"value":"42"}'
```

The returned string parses into `{value:"42"}`, not `{value:42}`

This issue does not exist for `int32`.

Is this some nuance in `JSON.stringify`, or is this a bug in `protobufjs`?

**Comment by dcodeIO** [comment]
In JavaScript, it's not possible to represent the full spectrum of a 64-bit integer as a number. JavaScript "Number"s are IEE754 doubles, which cannot safely represent a value larger than 2^53. That's why there is the dependency on [long.js](https://github.com/dcodeIO/long.js).

For the purpose of various conversions, there is also `Message.toObject` / `Message.fromObject´ with the former accepting a set of options. For instance, doing `MyMessage.toObject(myMessage, { long: Number })` and then running the result through JSON.stringify should give the desired, though possibly unsafe if there are values larger than 2^53, result.

**Comment by fiibbb** [comment]
Ah this is very helpful. Thanks a lot.

**Comment by erbhargavvyas** [comment]
The JSON `Number` supports up to 52 bits only so a number more than that will get rounded off.
